### ISSUE TITLE
shimming-toolbox command not found

### ISSUE THREAD

**Issue by KevinBerard** [shimming-toolbox/fsleyes-plugin-shimming-toolbox#12]
### Checklist

- [X] I've given this issue a self-descriptive, meaningful title (e.g. *Installation failure: problem creating launchers*)
- [X] I've described my environment
- [X] I've described the bug
- [X] I've described the steps to reproduce the behaviour
- [X] I've included screenshots
- [X] I've given this issue the correct labels

### Environment details

- [X] I followed the [installation instructions](https://shimming-toolbox.org/en/latest/getting_started/installation_gui.html)

Project version: 7c52ded8ec39678ea56cf6c556d55a52ff65ff6a

Operating System and version: Ubuntu21

Python version: 3.7 

Path to Python binary: /home/kb/anaconda3/envs/shim_venv/bin/python 

### Bug Description

When I try to use the command shimming-toolbox, the command is not found

### Reproduction Steps

1. Procede to the [instructions](https://shimming-toolbox.org/en/latest/getting_started/installation_st/linux.html) for the installation of shimming toolbox and having pytest give a 100% test result.
2. Install the FSLeyes plugin with the [instructions](https://shimming-toolbox.org/en/latest/getting_started/installation_gui.html)
3. Try to launch the FSLeyes with the plugin with the command "shimming-toolbox"

### Potential Reasons behind Bug:

Path for shimming toolbox not properly define during installation maybe.

### Screenshots:

![Screenshot from 2021-05-27 15-22-12](https://user-images.githubusercontent.com/83981856/119885903-66c4a280-bf00-11eb-9c66-6425ca8360fc.png)
![Screenshot from 2021-05-27 15-29-05](https://user-images.githubusercontent.com/83981856/119885905-66c4a280-bf00-11eb-90f0-74d7163f818f.png)

**Comment by ahill187** [comment]
If it installed properly, you should see the following lines in your `~./bashrc` file:

```
# FSLEYES_PLUGIN_SHIMMING_TOOLBOX (installed on 2021-05-07 09:47:59)
export PATH="/Users/work/shimming_toolbox/bin:$PATH"
export ST_DIR=/Users/work/shimming_toolbox
alias shimming-toolbox='/Users/work/shimming_toolbox/bin/shimming-toolbox.sh'

# SHIMMINGTOOLBOX (installed on 2021-05-07 09:48:25)
export PATH="/Users/work/shimming_toolbox/bin:$PATH"
export ST_DIR=/Users/work/shimming_toolbox
```

Are they at the bottom? Or is that your whole `~./bashrc` file?

**Comment by KevinBerard** [comment]
The screenshot is the bottom of my `~./bashrc`.  And the lines mentionned are not in the `~./bashrc`. I can put them mannualy and it will probably work, but I am wondering why the installation didn't go through.

**Comment by ahill187** [comment]
> The screenshot is the bottom of my `~./bashrc`. And the lines mentionned are not in the `~./bashrc`. I can put them mannualy and it will probably work, but I am wondering why the installation didn't go through.

That is very strange. I will try a clean install in VirtualBox on Ubuntu to see if I can find the issue.

**Comment by ahill187** [comment]
I tested it on a Ubuntu 20.04 VirtualBox via Vagrant. I used this `Vagrantfile`:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/focal64"

  # Provider-specific configuration so you can fine-tune various
  # backing providers for Vagrant. These expose provider-specific options.

  config.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 4
      vb.gui = true
      vb.customize ['modifyvm', :id, '--graphicscontroller', 'vmsvga']
  end


  # Folder Settings
  config.vm.synced_folder "../../", "/home/vagrant/src/fsleyes-plugin-shimming-toolbox/"

  # Provision Settings
  config.vm.provision "shell", path: "install.sh"

end
```

Here is the `install.sh` file I used:

```
# Update Packages
apt-get update
# Upgrade Packages
apt-get upgrade

# Basic Linux Stuff
apt-get install -y git
apt-get install -y make vim freeglut3 gcc
```

This was run as setup for the machine. Once it was set up, I used `ssh` to login to the virtual machine:

```
cd testing/vagrant_linux
vagrant ssh
```

Once I was into the virtual machine, I was logged in as the user `vagrant`. The user folder is `/home/vagrant`. The `home` folder is owned by `root`, and the `home/vagrant` folder is owned by the user `vagrant`.

To install `fsleyes-plugin-shimming-toolbox`:

```
cd /home/vagrant/src/fsleyes-plugin-shimming-toolbox
sudo make install
```

When it finished, the following lines were added to `/home/vagrant/.bashrc` (the local `bashrc` file):

```
# FSLEYES_PLUGIN_SHIMMING_TOOLBOX (installed on 2021-06-15 21:30:50)
export PATH="/home/vagrant/shimming_toolbox/bin:$PATH"
export ST_DIR=/home/vagrant/shimming_toolbox
alias shimming-toolbox='/home/vagrant/shimming_toolbox/bin/shimming-toolbox.sh'

# SHIMMINGTOOLBOX (installed on 2021-06-15 21:31:43)
export PATH="/home/vagrant/shimming_toolbox/bin:$PATH"
export ST_DIR=/home/vagrant/shimming_toolbox
```

The root `bashrc` file is under `/etc/bash.bashrc`. This file was not modified by the install.
