### ISSUE TITLE
Dcm2niix comes packaged with fsleyes but has and unsupported version

### ISSUE THREAD

**Issue by po09i** [shimming-toolbox/fsleyes-plugin-shimming-toolbox#14]
## Summary
I have dcm2niix installed on my computer (v1.0.20201102). When launching the plugin, it uses the version that got downloaded in `pst_venv`. That version is not supported by shimming-toolbox. (Which render st_dicom_to_nifti useless for realtime shimming)

## Additional info
![Screen Shot 2021-06-30 at 12 08 13](https://user-images.githubusercontent.com/47249340/123994960-dc0e1200-d99b-11eb-83e6-020eba16c903.png)

conda activate `pst_venv`
![Screen Shot 2021-06-30 at 12 09 02](https://user-images.githubusercontent.com/47249340/123995088-f7791d00-d99b-11eb-83c5-3e78ee09bfdb.png)

**Comment by po09i** [comment]
Using `conda uninstall dcm2niix` did not fix the problem since conda found inconsistencies in the package. I had to do `conda uninstall dcm2niix --force`

It will now use my local version of dcm2niix

**Comment by gaspardcereza** [comment]
The wrong version seems to be installed as a FSLeyes dependency. In [this issue on dcm2niix's GitHub](https://github.com/pauldmccarthy/fsleyes/issues/69), Paul McCarthy mentioned that he updated the version of dcm2niix coming along FSLeyes to the correct one so this problem should not occur anymore... @ahill187 do you now if we are installing the last release of FSLeyes here ?

**Comment by ahill187** [comment]
There were some bugs in the latest release of FSLeyes, so we are installing `fsleyes==0.34.2`. One of the bugs was the plugin not loading properly or showing up in the dropdown menu (OrthoView I think).

**Comment by ahill187** [comment]
# Testing on VirtualBox MacOS 10.14

To recreate this problem, I am using the `vagrant` method in our `testing` folder to create a `MacOS VirtualBox`. Please see the `README` for more details on this testing procedure.

1. Create virtual machine and ssh into it:

```
cd fsleyes-plugin-shimming-toolbox/testing/vagrant_mac
vagrant up
vagrant ssh
```

2. Install the plugin on the virtual machine:

```
cd src/fsleyes-plugin-shimming-toolbox
sudo make install
source /Users/vagrant/.bashrc
```

3. Activate the conda environment:

```
source /Users/vagrant/shimming_toolbox/python/etc/profile.d/conda.sh
conda activate pst_venv_1267b18e73341ad94da34474
```

4. Check the `dcm2niix` version:

```
conda list
```
<img width="521" alt="dcm2niix" src="https://user-images.githubusercontent.com/23019211/127216093-b8a7cb2d-ec50-437f-9bab-b27972839383.png">

## Results

`dcm2niix` version is `1.0.20190902`, as mentioned by @po09i above. We need to use a more recent version.

**Comment by gaspardcereza** [comment]
On my end (MacOS Catalina), I typed `make install` from a new conda environment (main branch), and when runing `dcm2niix -v`, it returns `v1.0.20201102`. So it seems to be working correctly

**Comment by po09i** [comment]
This has been resolved
