### ISSUE TITLE
Version checking not working

### ISSUE THREAD

**Issue by gaspardcereza** [shimming-toolbox/fsleyes-plugin-shimming-toolbox#33]
### Bug Description
So far, we use the following function to check if newer versions of the plugin are available:
```python
    def verify_version(self):
        """Check if the plugin version is the same as the one in the shimming-toolbox directory."""

        st_path = os.path.realpath(__file__)
        plugin_file = os.path.join(st_path, "gui", "st_plugin.py")

        plugin_file_exists = os.path.isfile(plugin_file)

        if not plugin_file_exists:
            return

        # Check the version of the plugin
        with open(plugin_file) as plugin_file_reader:
            plugin_file_lines = plugin_file_reader.readlines()

        plugin_file_lines = [x.strip() for x in plugin_file_lines]
        version_line = f'VERSION = "{VERSION}"'
        plugin_is_up_to_date = True
        version_found = False

        for lines in plugin_file_lines:
            if lines.startswith("VERSION = "):
                version_found = True
                if not lines == version_line:
                    plugin_is_up_to_date = False

        if version_found is False or plugin_is_up_to_date is False:
            message = """
                A more recent version of the ShimmingToolbox plugin was found in your
                ShimmingToolbox installation folder. You will need to replace the current
                FSLeyes plugin with the new one.
                To proceed, go to: File -> Load plugin -> st_plugin.py. Then, restart FSLeyes.
            """
            self.show_message(message, "Warning")
        return
```

But, as is, it does not check anything.

### Potential Reasons behind Bug:

 The `plugin_file` had the following value:
 `/Users/gaspard/git/fsleyes-plugin-shimming-toolbox/fsleyes_plugin_shimming_toolbox/st_plugin.py/gui/st_plugin.py`

This path obviously does not exist and no version is checked.
I think we might have created this function when the plugin was still part of the `shimming-toolbox` repository, or simply copied it from another repository.

### What should we do ?

As we currently are in the process of simplifying our code organization (see [this issue](https://github.com/shimming-toolbox/shimming-toolbox/issues/369)), I would simply remove this function for now as it does nothing and might not even be useful anymore depending on what we decide to do with our installation. 
However, I wanted to keep track of it by opening this issue, so that we can potentially come back to it if needed in the future.

**Comment by po09i** [comment]
The function was removed
