### ISSUE TITLE
Fix default folder of plugin input/output

### ISSUE THREAD

**Issue by ahill187** [shimming-toolbox/fsleyes-plugin-shimming-toolbox#5]
The default folder for the plugin pull request is currently the python folder in the venv; we should change it to somewhere else.

See pull request: https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/2

**Comment by ahill187** [comment]
Changed default folder to the directory from which the file is called (the directory of your shell): https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/2/commits/7e1368019bf9137115ca459ffec192c111b9053b

**Comment by po09i** [comment]
Probably a related issue: https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/2#issuecomment-828734414
