### ISSUE TITLE
Error: No bitmap handler for type 15 defined

### ISSUE THREAD

**Issue by ahill187** [shimming-toolbox/fsleyes-plugin-shimming-toolbox#6]
When trying to run some of the commands in FSLeyes, we get the following error (Mac OSX Catalina):

![image](https://user-images.githubusercontent.com/23019211/115431367-0f713b00-a1ba-11eb-8a8c-2e72a1cee7cd.png)

**Comment by gaspardcereza** [comment]
I get a similar error when trying to open a nifti (obtained by running dcm2niix on data from the MNI). It also happens when trying to open a spinal cord segmentation performed on these same data using set. I wasn't using any of the ST functionnalities so I think this problem might be caused by FSLeyes and not our plugin.

```
15:52:55: can't open file '/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/verticalReset32.png' (error 2: No such file or directory)
15:52:55: Failed to load image from file "/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/verticalReset32.png".
15:52:55: no bitmap handler for type 15 defined.
15:52:55: can't open file '/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/twocmaps24.png' (error 2: No such file or directory)
15:52:55: Failed to load image from file "/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/twocmaps24.png".
15:52:55: no bitmap handler for type 15 defined.
15:52:55: can't open file '/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/onecmap24.png' (error 2: No such file or directory)
15:52:55: Failed to load image from file "/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/onecmap24.png".
15:52:55: no bitmap handler for type 15 defined.
```

**Comment by ahill187** [comment]
> I get a similar error when trying to open a nifti (obtained by running dcm2niix on data from the MNI). It also happens when trying to open a spinal cord segmentation performed on these same data using set. I wasn't using any of the ST functionnalities so I think this problem might be caused by FSLeyes and not our plugin.
> 
> ```
> 15:52:55: can't open file '/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/verticalReset32.png' (error 2: No such file or directory)
> 15:52:55: Failed to load image from file "/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/verticalReset32.png".
> 15:52:55: no bitmap handler for type 15 defined.
> 15:52:55: can't open file '/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/twocmaps24.png' (error 2: No such file or directory)
> 15:52:55: Failed to load image from file "/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/twocmaps24.png".
> 15:52:55: no bitmap handler for type 15 defined.
> 15:52:55: can't open file '/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/onecmap24.png' (error 2: No such file or directory)
> 15:52:55: Failed to load image from file "/Users/gaspard/miniconda3/lib/python3.8/site-packages/fsleyes/../assets/icons/onecmap24.png".
> 15:52:55: no bitmap handler for type 15 defined.
> ```

What is data from the MNI? Where could I find that to try and reproduce the error?

**Comment by gaspardcereza** [comment]
Do you have an access to Duke ? It's under MRI/mni-7t and it's the acquisition called 'TFL_SAG_2MMISO_384MM_REFV_0008' from the acdc_spine7t_005p

**Comment by ahill187** [comment]
> Do you have an access to Duke ? It's under MRI/mni-7t and it's the acquisition called 'TFL_SAG_2MMISO_384MM_REFV_0008' from the acdc_spine7t_005p

I don't think so...do you know why it is this file in particular? Do you get the same error with other files?

**Comment by gaspardcereza** [comment]
It only happens with the data from some sequences. I think it has nothing to do with our plugin but is related to fsleyes

**Comment by ahill187** [comment]
Is there anything noticeably different about the sequences that you get the error on?

**Comment by gaspardcereza** [comment]
There probably is something different but I couldn't find out what it is... Maybe some missing dicom tag that would make the conversion from dicom to nifti going wrong but they are so many of them that it's hard to tell which one could be responsible for this error.

**Comment by po09i** [comment]
I had a similar problem when trying to save files where the default path was within the venv since the plugin tries to import the file automatically after its creation. I'm not sure if this was the specific error message though.

**Comment by ahill187** [comment]
Issue seems to have resolved here: https://github.com/shimming-toolbox/fsleyes-plugin-shimming-toolbox/pull/2#issuecomment-832076449
